### ISSUE TITLE
AttributeError: 'Unset' object has no attribute 'REQUEST'

### ISSUE THREAD

**Issue by zopyx** [bluedynamics/yafowil.plone#12]
I am receiving the following error with this code. Is this due to Plone 5 incompatibility?

https://github.com/xml-director/xmldirector.demo/blob/master/xmldirector/demo/demo/yafowil_form.py

```
Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module Products.Five.browser.metaconfigure, line 485, in __call__
Module Products.Five.browser.pagetemplatefile, line 125, in __call__
Module Products.Five.browser.pagetemplatefile, line 59, in __call__
Module zope.pagetemplate.pagetemplate, line 132, in pt_render
Module five.pt.engine, line 98, in __call__
Module z3c.pt.pagetemplate, line 163, in render
Module chameleon.zpt.template, line 261, in render
Module chameleon.template, line 191, in render
Module chameleon.template, line 171, in render
Module b886c35218496fb9ebd95aee4d79621f.py, line 200, in render
Module d1bf3fbec8b0c7dd9a22b2485a68155a.py, line 1223, in render_master
Module d1bf3fbec8b0c7dd9a22b2485a68155a.py, line 420, in render_content
Module b886c35218496fb9ebd95aee4d79621f.py, line 188, in __fill_content_core
Module b886c35218496fb9ebd95aee4d79621f.py, line 90, in render_content_core
Module five.pt.expressions, line 161, in __call__
Module xmldirector.demo.demo.yafowil_form, line 38, in form_renderer
Module yafowil.base, line 314, in __call__
Module yafowil.base, line 422, in _runpreprocessors
yafowil widget processing info:

path: demo_form
blueprints: ['form']
task: preprocessor
description: failed at '__GLOBAL__i'
Module yafowil.plone.connectors, line 55, in plone_preprocessor
Module yafowil.plone.connectors, line 15, in __init__
AttributeError: 'Unset' object has no attribute 'REQUEST'

```

**Comment by rnixx** [comment]
If you're working with p5 please use the plone5 branch.

You can also use provided form base classes from yafowil.plone.

Either this one if you define the form in python
https://github.com/bluedynamics/yafowil.plone/blob/plone5/src/yafowil/plone/form.py#L25

or this one if you want to use YAML for form definition
https://github.com/bluedynamics/yafowil.plone/blob/plone5/src/yafowil/plone/form.py#L40

Also have a look how render_form is implemented. It uses the Controller object for actual form processing, which is missing in your code
https://github.com/bluedynamics/yafowil.plone/blob/plone5/src/yafowil/plone/form.py#L13

**Comment by rnixx** [comment]
Did my response help? Can we close this issue?

**Comment by zopyx** [comment]
Haven't had a chance to look into the issue again..

**Comment by rnixx** [comment]
OK. Please also use master branch of yafowil itself when finally trying this.

**Comment by jensens** [comment]
FYI: I released yafowil and yafowil.plone now, plone5 branch is merged and gone.

**Comment by jensens** [comment]
Looks like this one was solved. I close it, please reopen if I am wrong!
