### ISSUE TITLE
context undefined

### ISSUE THREAD

**Issue by jensens** [bluedynamics/yafowil.plone#17]
https://github.com/bluedynamics/yafowil.plone/blob/ebfca489db9b136a796771f04cb3c64c88b66bfb/src/yafowil/plone/form.py#L29

I do not know exactly when it is expected to run into the fallback, anyway, context is undefined here.

**Comment by rnixx** [comment]
fixed via https://github.com/bluedynamics/yafowil.plone/commit/2379128f56f408fe396d0e09b23268e49909a8e0
