### ISSUE TITLE
yafowil.plone throws errors in Plone 6, because of requireJS

### ISSUE THREAD

**Issue by MrTango** [bluedynamics/yafowil.plone#41]
In Plone 6 we don't have require js anymore, but yafowil.plone still has code in it.
https://github.com/bluedynamics/yafowil.plone/blob/f1c3419528244507eee3cb7d2a48c1306dcc94ab/src/yafowil/plone/resources.py#L97
This breaks pas.plugins.ldap schema editor.

**Comment by mliebischer** [comment]
Could this issue be closed? Seems to be fixed by: https://github.com/bluedynamics/yafowil.plone/pull/42
