### ISSUE TITLE
get_ajaxselect_options is removed in Plone 6

### ISSUE THREAD

**Issue by 1letter** [bluedynamics/yafowil.plone#47]
in src/yafowil/plone/autoform/factories.py

https://community.plone.org/t/plone-6-0-7-soft-released/17901/2?u=1letter

**Comment by krissik** [comment]
Will there be a released version of this fix in the near future?

**Comment by 1letter** [comment]
@krissik https://pypi.org/project/yafowil.plone/5.0.0a1/
