### ISSUE TITLE
plone.app.widgets is deprecated in Plone 6

### ISSUE THREAD

**Issue by szakitibi** [bluedynamics/yafowil.plone#49]
There are imports which assume `plone.app.widgets` is still part of Plone 6.

https://github.com/bluedynamics/yafowil.plone/blob/2fdafd6aff4bda2c4fa940c4a7a45263ce4a9dd5/src/yafowil/plone/widgets/datetime.py#L6-L7

https://github.com/bluedynamics/yafowil.plone/blob/2fdafd6aff4bda2c4fa940c4a7a45263ce4a9dd5/src/yafowil/plone/widgets/relation.py#L3-L4

https://github.com/bluedynamics/yafowil.plone/blob/2fdafd6aff4bda2c4fa940c4a7a45263ce4a9dd5/src/yafowil/plone/widgets/richtext.py#L1

See https://github.com/plone/plone.app.widgets/issues/220, https://github.com/plone/plone.app.z3cform/pull/155

**Comment by rnixx** [comment]
Release is out. Thank you (https://pypi.org/project/yafowil.plone/5.0.0a2/)
